GET http://localhost:8000

###
POST http://localhost:8000/create-account
Content-Type: application/json


###
POST  http://localhost:8000/login
Content-Type: application/json

{
    "email":"nziokamtk@gmail.com",
    "password":"test@User123."
}

###
GET http://localhost:8000/get-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY4ZWFjMzQ5MGNhYjE0MmRhZTUwODY0MSIsImZ1bGxOYW1lIjoiU3RlcGhlbiBLaXZ1dGh1IE11dHVrdSIsImVtYWlsIjoic3RldmVrdkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IlNLTTAxMSIsImNyZWF0ZWRPbiI6IjIwMjUtMTAtMTFUMjA6NDg6NDYuNTY0WiIsIl9fdiI6MH0sImlhdCI6MTc2MDM1Mjg0OSwiZXhwIjoxNzYwNTYyODQ5fQ.rymp_OHuV7NzkhXUJA9KkJjXjgjbW1oZHrb-LoADRcw

###
POST http://localhost:8000/add-note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY4ZWFjMzQ5MGNhYjE0MmRhZTUwODY0MSIsImZ1bGxOYW1lIjoiU3RlcGhlbiBLaXZ1dGh1IE11dHVrdSIsImVtYWlsIjoic3RldmVrdkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IlNLTTAxMSIsImNyZWF0ZWRPbiI6IjIwMjUtMTAtMTFUMjA6NDg6NDYuNTY0WiIsIl9fdiI6MH0sImlhdCI6MTc2MDM1Mjg0OSwiZXhwIjoxNzYwNTYyODQ5fQ.rymp_OHuV7NzkhXUJA9KkJjXjgjbW1oZHrb-LoADRcw

###
PUT http://localhost:8000/edit-note/68e911a60446d4a4b76fbb9c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY4ZThiZWQzYWZmNWJhYjBjNWVjZWYzOSIsImZ1bGxOYW1lIjoiTnppb2thIER6bmllbCBNdXR1a3UiLCJlbWFpbCI6Im56aW9rYW10a0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3RVc2VyMTIzLiIsImNyZWF0ZWRPbiI6IjIwMjUtMTAtMTBUMDc6NTc6MDguMTY4WiIsIl9fdiI6MH0sImlhdCI6MTc2MDA5MDUwOCwiZXhwIjoxNzYwMzAwNTA4fQ.B8XdOB7LFwzj32_uscrG7haLNZdAJ23XGdqHKEPVQEY

###
GET http://localhost:8000/get-all-notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY4ZThiZWQzYWZmNWJhYjBjNWVjZWYzOSIsImZ1bGxOYW1lIjoiTnppb2thIER6bmllbCBNdXR1a3UiLCJlbWFpbCI6Im56aW9rYW10a0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3RVc2VyMTIzLiIsImNyZWF0ZWRPbiI6IjIwMjUtMTAtMTBUMDc6NTc6MDguMTY4WiIsIl9fdiI6MH0sImlhdCI6MTc2MDA5MDUwOCwiZXhwIjoxNzYwMzAwNTA4fQ.B8XdOB7LFwzj32_uscrG7haLNZdAJ23XGdqHKEPVQEY

###
DELETE http://localhost:8000/delete-note/68e913080446d4a4b76fbb9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY4ZThiZWQzYWZmNWJhYjBjNWVjZWYzOSIsImZ1bGxOYW1lIjoiTnppb2thIER6bmllbCBNdXR1a3UiLCJlbWFpbCI6Im56aW9rYW10a0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3RVc2VyMTIzLiIsImNyZWF0ZWRPbiI6IjIwMjUtMTAtMTBUMDc6NTc6MDguMTY4WiIsIl9fdiI6MH0sImlhdCI6MTc2MDA5MDUwOCwiZXhwIjoxNzYwMzAwNTA4fQ.B8XdOB7LFwzj32_uscrG7haLNZdAJ23XGdqHKEPVQEY

###
PUT http://localhost:8000/update-note-pinned/68e911a60446d4a4b76fbb9c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY4ZThiZWQzYWZmNWJhYjBjNWVjZWYzOSIsImZ1bGxOYW1lIjoiTnppb2thIER6bmllbCBNdXR1a3UiLCJlbWFpbCI6Im56aW9rYW10a0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3RVc2VyMTIzLiIsImNyZWF0ZWRPbiI6IjIwMjUtMTAtMTBUMDc6NTc6MDguMTY4WiIsIl9fdiI6MH0sImlhdCI6MTc2MDA5MDUwOCwiZXhwIjoxNzYwMzAwNTA4fQ.B8XdOB7LFwzj32_uscrG7haLNZdAJ23XGdqHKEPVQEY

###
GET http://localhost:8000/search-note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY4ZThiZWQzYWZmNWJhYjBjNWVjZWYzOSIsImZ1bGxOYW1lIjoiTnppb2thIERhbmllbCBNdXR1a3UiLCJlbWFpbCI6Im56aW9rYW10a0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3RAVXNlcjEyMy4iLCJjcmVhdGVkT24iOiIyMDI1LTEwLTEwVDA3OjU3OjA4LjE2OFoiLCJfX3YiOjB9LCJpYXQiOjE3NjA1MzQzODQsImV4cCI6MTc2MDc0NDM4NH0.pOd3z4DtoEWjriQcqmgnmQjmk_k7d9QrNUl1AUZw-yw
